use super::{IllegalInstruction, NativeError};
use crate::interpreter::{ByteString, MultiValue};
use std::borrow::Cow;
use std::rc::Rc;

#[derive(Debug, PartialEq, Clone)]
pub enum RuntimeErrorData {
    IllegalInstruction(IllegalInstruction),
    InvalidRef,
    MissingMain,
    StackOverflow,
    NotAFunction,
    MetatableChainTooLong,
    AttemptToIndexInvalid,
    AttemptToConcatInvalid,
    NoLength,
    InvalidCompare,
    InvalidArithmetic,
    DivideByZero,
    NoIntegerRepresentation(f64),
    InitialValueMustBeNumber,
    LimitMustBeNumber,
    StepMustBeNumber,
    OutOfBounds,
    DeadCoroutine,
    ResumedNonSuspendedCoroutine,
    Yield(MultiValue),
    InvalidYield,
    UnhandledYield,
    YieldMissingContinuation,
    /// Bad argument passed to a function. Generated by [MultiValue::unpack_args()] and [MultiValue::unpack_modified_args()]
    BadArgument {
        /// Argument position (usually starts from 1).
        position: usize,
        /// Underlying error returned when converting argument to a Lua value.
        reason: Rc<RuntimeErrorData>,
    },
    ExpectedType {
        expected: &'static str,
        received: &'static str,
    },
    NativeError(NativeError),
    String(Cow<'static, str>),
    ByteString(ByteString),
}

impl From<IllegalInstruction> for RuntimeErrorData {
    fn from(value: IllegalInstruction) -> Self {
        Self::IllegalInstruction(value)
    }
}
